blank_issues_enabled: false
contact_links:
    - name: Documentation Issue
      url: https://github.com/VarboxInternational/varbox-docs
      about: For documentation issues, open an issue or pull request in our docs repo
